import type { ThemeName, ThemeVariableConfig } from "../types";

/**
Z-index:

Modal - 100
Popper - 110
DropDown - 120
PopConfirm - 130
Select - 140
Search - 140
Notification - 150
Message - 160
Tooltip - 170
 */

export const THEME_CONFIG: Record<ThemeName, ThemeVariableConfig> = {
  light: {
    common: {
      transition: {
        "ksd-transition-fast": "0.1s",
        "ksd-transition-mid": "0.2s",
        "ksd-transition-slow": "0.3s",
      },
      sizes: {
        "ksd-control-height-sm": "24px",
        "ksd-control-height": "32px",
        "ksd-control-height-lg": "40px",
        "ksd-control-interactive-size": "16px",
      },

      shadow: {
        "ksd-shadow":
          "0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)",
        "ksd-shadow-secondary":
          "0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)",
        "ksd-shadow-tertiary":
          "0 1px 2px 0 rgba(0, 0, 0, 0.03), 0 1px 6px -1px rgba(0, 0, 0, 0.02), 0 2px 4px 0 rgba(0, 0, 0, 0.02)",
        "ksd-shadow-accent":
          "0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)",
        "ksd-shadow-bottom":
          "0 -6px 16px 0 rgba(0, 0, 0, 0.08), 0 -3px 6px -4px rgba(0, 0, 0, 0.12), 0 -9px 28px 8px rgba(0, 0, 0, 0.05)",
        "ksd-shadow-left":
          "6px 0 16px 0 rgba(0, 0, 0, 0.08), 3px 0 6px -4px rgba(0, 0, 0, 0.12), 9px 0 28px 8px rgba(0, 0, 0, 0.05)",
        "ksd-shadow-right":
          "-6px 0 16px 0 rgba(0, 0, 0, 0.08), -3px 0 6px -4px rgba(0, 0, 0, 0.12), -9px 0 28px 8px rgba(0, 0, 0, 0.05)",
        "ksd-shadow-top":
          "0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)",
      },
      border: {
        "ksd-border-radius-xs": "2px",
        "ksd-border-radius-sm": "4px",
        "ksd-border-radius": "6px",
        "ksd-border-radius-lg": "8px",
        "ksd-border-radius-outer": "4px",
        "ksd-line-type": "solid",
        "ksd-line-width": "1px",
        "ksd-outline-type": "solid",
        "ksd-outline-width": "3px",
      },
      padding: {
        "ksd-padding-xxs": "4px",
        "ksd-padding-xs": "8px",
        "ksd-padding-sm": "12px",
        "ksd-padding": "16px",
        "ksd-padding-md": "20px",
        "ksd-padding-lg": "24px",
        "ksd-padding-xl": "32px",
      },
      margin: {
        "ksd-margin-xxs": "4px",
        "ksd-margin-xs": "8px",
        "ksd-margin-sm": "12px",
        "ksd-margin": "16px",
        "ksd-margin-md": "20px",
        "ksd-margin-lg": "24px",
        "ksd-margin-xl": "32px",
        "ksd-margin-xxl": "48px",
      },
      font: {
        "ksd-font-family": "Nunito",
        "ksd-font-weight": "400",
        "ksd-font-weight-strong": "600",
        "ksd-line-height": "1.5",
        "ksd-line-height-lg": "1.5",
        "ksd-line-height-sm": "1.6666666666666667",
        "ksd-font-size-sm": "12px",
        "ksd-font-size": "14px",
        "ksd-font-size-lg": "16px",
        "ksd-font-size-xl": "20px",
      },
      other: {
        "ksd-popup-z-index": "110",
        "ksd-opacity-loading": "0.65",
        "ksd-tooltip-z-index": "170",
      },
      colors: {
        "ksd-bg-color": "#ffffff",
        "ksd-bg-container-color": "#ffffff",
        "ksd-bg-sidebar-color": "#ffffff",
        "ksd-bg-header-color": "#ffffff",
        "ksd-bg-modal-color": "#ffffff",
        "ksd-bg-popper-color": "#ffffff",
        "ksd-bg-notice-color": "#ffffff",
        "ksd-bg-tooltip-color": "rgba(0,0,0,0.85)",
        "ksd-bg-mask-color": "rgba(0,0,0,0.45)",
        "ksd-bg-fill-color": "rgba(0,0,0,0.04)",
        "ksd-bg-fill-hover-color": "rgba(0,0,0,0.06)",
        "ksd-bg-disabled-color": "rgba(0, 0, 0, 0.04)",
        "ksd-bg-hover-color": "rgba(0, 0, 0, 0.04)",
        "ksd-bg-active-color": "rgba(0, 0, 0, 0.15)",
        "ksd-text-main-color": "rgba(0, 0, 0, 0.88)",
        "ksd-text-main-disabled-color": "rgba(0, 0, 0, 0.25)",
        "ksd-text-main-hover-color": "",
        "ksd-text-secondary-color": "#8c8c8c",
        "ksd-text-secondary-disabled-color": "rga(140, 140, 140, 0.25)",
        "ksd-text-secondary-hover-color": "",
        "ksd-text-tertiary-color": "rgba(0, 0, 0, 0.45)",
        "ksd-text-quaternary-color": "rgba(0, 0, 0, 0.25)",
        "ksd-text-reverse-color": "#ffffff",
        "ksd-text-reverse-secondary-color": "",
        "ksd-text-placeholder-color": "rgba(0, 0, 0, 0.25)",
        "ksd-border-color": "#d9d9d9",
        "ksd-border-disabled-color": "#d9d9d9",
        "ksd-border-hover-color": "",
        "ksd-divider-color": "rgba(5,5,5,0.06)",
        "ksd-icon-color": "rgba(0, 0, 0, 0.45)",
        "ksd-icon-hover-color": "#262626",
        "ksd-outline-color": "#91caff",
        "ksd-accent-color": "#1677ff",
        "ksd-accent-hover-color": "#4096ff",
        "ksd-accent-active-color": "#0958d9",
        "ksd-accent-bg-color": "#e6f4ff",
        "ksd-accent-bg-hover-color": "#bae0ff",
        "ksd-accent-border-color": "#91caff",
        "ksd-accent-border-hover-color": "#69b1ff",
        "ksd-error-color": "#ff4d4f",
        "ksd-error-active-color": "#d9363e",
        "ksd-error-hover-color": "#ff7875",
        "ksd-error-bg-color": "#fff2f0",
        "ksd-error-bg-active-color": "#ffccc7",
        "ksd-error-bg-hover-color": "#fff1f0",
        "ksd-error-border-color": "#ffccc7",
        "ksd-error-border-hover-color": "#ffa39e",
        "ksd-warning-color": "#faad14",
        "ksd-warning-active-color": "#d48806",
        "ksd-warning-hover-color": "#ffc53d",
        "ksd-warning-bg-color": "#fffbe6",
        "ksd-warning-bg-active-color": "",
        "ksd-warning-bg-hover-color": "#fff1b8",
        "ksd-warning-border-color": "#ffe58f",
        "ksd-warning-border-hover-color": "#ffd666",
        "ksd-success-color": "#52c41a",
        "ksd-success-active-color": "#389e0d",
        "ksd-success-hover-color": "#73d13d",
        "ksd-success-bg-color": "#f6ffed",
        "ksd-success-bg-active-color": "",
        "ksd-success-bg-hover-color": "#d9f7be",
        "ksd-success-border-color": "#b7eb8f",
        "ksd-success-border-hover-color": "#95de64",
        "ksd-info-color": "#1677ff",
        "ksd-info-active-color": "#0958d9",
        "ksd-info-hover-color": "#69b1ff",
        "ksd-info-bg-color": "#e6f4ff",
        "ksd-info-bg-active-color": "",
        "ksd-info-bg-hover-color": "#bae0ff",
        "ksd-info-border-color": "#91caff",
        "ksd-info-border-hover-color": "#69b1ff",
      },
    },
    components: {
      collapse: {
        "ksd-collapse-header-bg": "rgba(0, 0, 0, 0.02)",
        "ksd-collapse-body-bg": "var(--ksd-bg-container-color)",
      },
      divider: {
        "ksd-divider-width": "1px",
      },
      button: {
        "ksd-button-bg": "var(--ksd-bg-color)",
        "ksd-button-border": "var(--ksd-border-color)",
        "ksd-button-padding": "15px",
        "ksd-button-padding-lg": "15px",
        "ksd-button-padding-sm": "7px",
        "ksd-button-bg-disabled-color": "var(--ksd-bg-disabled-color)",
        "ksd-button-border-disabled-color": "var(--ksd-border-disabled-color)",
        "ksd-button-text-disabled-color": "var(--ksd-text-main-disabled-color)",
      },
      input: {
        "ksd-input-padding-block": "4px",
        "ksd-input-padding-inline": "11px",
        "ksd-input-padding-block-sm": "0px",
        "ksd-input-padding-inline-sm": "7px",
        "ksd-input-padding-block-lg": "7px",
        "ksd-input-padding-inline-lg": "11px",
        "ksd-input-active-shadow": "0 0 0 2px rgba(5,145,255,0.1)",
      },
      radio: {
        "ksd-radio-dot-size": 6,
        "ksd-radio-size": 16,
        "ksd-radio-dot-color": "#ffffff",
        "ksd-radio-button-padding-inline": "15px",
      },
      slider: {
        "ksd-slider-control-size": "10px",
        "ksd-slider-rail-size": "4px",
        "ksd-slider-handle-size": "10px",
        "ksd-slider-handle-size-hover": "12px",
        "ksd-slider-handle-line-width": "2px",
        "ksd-slider-handle-line-width-hover": "2.5px",
        "ksd-slider-rail-bg": "var(--ksd-bg-fill-color)",
        "ksd-slider-rail-hover-bg": "var(--ksd-bg-fill-hover-color)",
        "ksd-slider-track-bg": "var(--ksd-accent-border-color)",
        "ksd-slider-track-hover-bg": "var(--ksd-accent-border-hover-color)",
        "ksd-slider-handle-color": "var(--ksd-accent-border-color)",
        "ksd-slider-handle-active-color": "var(--ksd-accent-color)",
        "ksd-slider-handle-active-outline-color": "rgba(22, 119, 255, 0.2)",
        "ksd-slider-handle-color-disabled": "#bfbfbf",
        "ksd-slider-track-bg-disabled": "var(--ksd-bg-disabled-color)",
      },
      switch: {
        "ksd-switch-track-height": "20px",
        "ksd-switch-track-height-sm": "16px",
        "ksd-switch-track-min-width": "40px",
        "ksd-switch-track-min-width-sm": "28px",
        "ksd-switch-track-padding": "2px",
        "ksd-switch-handle-bg": "#fff",
        "ksd-switch-handle-size": "16px",
        "ksd-switch-handle-size-sm": "12px",
        "ksd-switch-handle-shadow": "0 2px 4px 0 rgba(0, 35, 11, 0.2)",
        "ksd-switch-inner-min-margin": "9px",
        "ksd-switch-inner-max-margin": "24px",
        "ksd-switch-inner-min-margin-sm": "6px",
        "ksd-switch-inner-max-margin-sm": "18px",
        "ksd-switch-bg-unchecked-color": "var(--ksd-text-quaternary-color)",
        "ksd-switch-bg-unchecked-hover-color": "var(--ksd-text-tertiary-color)",
        "ksd-switch-checked-color": "#ffffff",
        "ksd-switch-unchecked-color": "#ffffff",
      },
      popper: {
        "ksd-popper-inner-padding": "12px",
        "ksd-popper-z-index": "110",
      },
      dropdown: {
        "ksd-dropdown-inner-padding": "5px 12px",
        "ksd-dropdown-inner-padding-lg": "12px",
        "ksd-dropdown-inner-min-width-lg": "150px",
        "ksd-dropdown-bg-item-color": "var(--ksd-bg-hover-color)",
        "ksd-dropdown-z-index": "120",
      },
      select: {
        "ksd-select-internal_fixed_item_margin": "2px",
        "ksd-select-z-index": "140",
        "ksd-select-option-selected-color": "var(--ksd-text-main-color)",
        "ksd-select-option-selected-font-weight": "var(--ksd-font-weight-strong)",
        "ksd-select-option-selected-bg": "var(--ksd-accent-bg-color)",
        "ksd-select-option-active-bg": "var(--ksd-bg-hover-color)",
        "ksd-select-option-padding": "5px 12px",
        "ksd-select-option-font-size": "var(--ksd-font-size)",
        "ksd-select-option-line-height": "var(--ksd-line-height)",
        "ksd-select-option-height": "var(--ksd-control-height)",
        "ksd-select-single-item-height-lg": "var(--ksd-control-height-lg)",
        "ksd-select-multiple-item-bg": "rgba(0, 0, 0, 0.06)",
        "ksd-select-multiple-item-border-color": "transparent",
        "ksd-select-multiple-item-height": "24px",
        "ksd-select-multiple-item-height-sm": "16px",
        "ksd-select-multiple-item-height-lg": "32px",
        "ksd-select-show-arrow-padding-inline-end": "18px",
        "ksd-select-selector-padding-sm": "8px",
      },
      popconfirm: {
        "ksd-pop-confirm-inner-padding": "12px",
        "ksd-pop-confirm-z-index": "130",
      },
      message: {
        "ksd-message-z-index": "160",
        "ksd-message-content-bg": "var(--ksd-bg-notice-color)",
        "ksd-message-content-padding": "9px 12px",
      },
      notification: {
        "ksd-notification-z-index": "150",
        "ksd-notification-width": "384px",
        "ksd-notification-block-margin": "24px",
        "ksd-notification-inline-margin": "24px",
        "ksd-notification-blur-bg-color": "transparent",
      },
      modal: {
        "ksd-modal-footer-bg": "transparent",
        "ksd-modal-header-bg": "var(--ksd-bg-modal-color)",
        "ksd-modal-title-line-height": "1.5",
        "ksd-modal-title-font-size": "16px",
        "ksd-modal-content-bg": "var(--ksd-bg-modal-color)",
        "ksd-modal-title-color": "var(--ksd-text-main-color)",
        "ksd-modal-content-padding": "20px 24px",
        "ksd-modal-header-padding": "0px",
        "ksd-modal-header-border-bottom": "none",
        "ksd-modal-header-margin-bottom": "8px",
        "ksd-modal-body-padding": "0px",
        "ksd-modal-footer-padding": "0px",
        "ksd-modal-footer-border-top": "none",
        "ksd-modal-footer-border-radius": "0px",
        "ksd-modal-footer-margin-top": "12px",
        "ksd-modal-margin-block": "100px",
        "ksd-modal-z-index": "100",
      },
      tag: {
        "ksd-tag-bg-color-magenta": "#fff0f6",
        "ksd-tag-text-color-magenta": "#c41d7f",
        "ksd-tag-border-color-magenta": "#ffadd2",
        "ksd-tag-bg-color-red": "#fff1f0",
        "ksd-tag-text-color-red": "#cf1322",
        "ksd-tag-border-color-red": "#ffa39e",
        "ksd-tag-bg-color-volcano": "#fff2e8",
        "ksd-tag-text-color-volcano": "#d4380d",
        "ksd-tag-border-color-volcano": "#ffbb96",
        "ksd-tag-bg-color-orange": "#fff7e6",
        "ksd-tag-text-color-orange": "#d46b08",
        "ksd-tag-border-color-orange": "#ffd591",
        "ksd-tag-bg-color-gold": "#fffbe6",
        "ksd-tag-text-color-gold": "#d48806",
        "ksd-tag-border-color-gold": "#ffe58f",
        "ksd-tag-bg-color-lime": "#fcffe6",
        "ksd-tag-text-color-lime": "#7cb305",
        "ksd-tag-border-color-lime": "#eaff8f",
        "ksd-tag-bg-color-green": "#f6ffed",
        "ksd-tag-text-color-green": "#389e0d",
        "ksd-tag-border-color-green": "#b7eb8f",
        "ksd-tag-bg-color-cyan": "#e6fffb",
        "ksd-tag-text-color-cyan": "#08979c",
        "ksd-tag-border-color-cyan": "#87e8de",
        "ksd-tag-bg-color-blue": "#e6f4ff",
        "ksd-tag-text-color-blue": "#0958d9",
        "ksd-tag-border-color-blue": "#91caff",
        "ksd-tag-bg-color-geekblue": "#f0f5ff",
        "ksd-tag-text-color-geekblue": "#1d39c4",
        "ksd-tag-border-color-geekblue": "#adc6ff",
        "ksd-tag-bg-color-purple": "#f9f0ff",
        "ksd-tag-text-color-purple": "#531dab",
        "ksd-tag-border-color-purple": "#d3adf7",
        "ksd-tag-bg-color-success": "var(--ksd-success-bg-color)",
        "ksd-tag-text-color-success": "var(--ksd-success-color)",
        "ksd-tag-border-color-success": "var(--ksd-success-border-color)",
        "ksd-tag-bg-color-processing": "var(--ksd-info-bg-color)",
        "ksd-tag-text-color-processing": "var(--ksd-info-color)",
        "ksd-tag-border-color-processing": "var(--ksd-info-border-color)",
        "ksd-tag-bg-color-error": "var(--ksd-error-bg-color)",
        "ksd-tag-text-color-error": "var(--ksd-error-color)",
        "ksd-tag-border-color-error": "var(--ksd-error-border-color)",
        "ksd-tag-bg-color-warning": "var(--ksd-warning-bg-color)",
        "ksd-tag-text-color-warning": "var(--ksd-warning-color)",
        "ksd-tag-border-color-warning": "var(--ksd-warning-border-color)",
        "ksd-tag-default-color": "var(--ksd-text-main-color)",
        "ksd-tag-default-bg": "#fafafa",
      },
      skeleton: {
        "ksd-skeleton-gradient-from-color": "rgba(0, 0, 0, 0.06)",
        "ksd-skeleton-gradient-to-color": "rgba(0, 0, 0, 0.15)",
        "ksd-skeleton-title-height": "16px",
        "ksd-skeleton-block-radius": "4px",
      },
    },
  },
  dark: {
    common: {
      transition: {
        "ksd-transition-fast": "0.1s",
        "ksd-transition-mid": "0.2s",
        "ksd-transition-slow": "0.3s",
      },
      sizes: {
        "ksd-control-height-sm": "24px",
        "ksd-control-height": "32px",
        "ksd-control-height-lg": "40px",
        "ksd-control-interactive-size": "16px",
      },

      shadow: {
        "ksd-shadow":
          "0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)",
        "ksd-shadow-secondary":
          "0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)",
        "ksd-shadow-tertiary":
          "0 1px 2px 0 rgba(0, 0, 0, 0.03), 0 1px 6px -1px rgba(0, 0, 0, 0.02), 0 2px 4px 0 rgba(0, 0, 0, 0.02)",
        "ksd-shadow-accent":
          "0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)",
        "ksd-shadow-bottom":
          "0 -6px 16px 0 rgba(0, 0, 0, 0.08), 0 -3px 6px -4px rgba(0, 0, 0, 0.12), 0 -9px 28px 8px rgba(0, 0, 0, 0.05)",
        "ksd-shadow-left":
          "6px 0 16px 0 rgba(0, 0, 0, 0.08), 3px 0 6px -4px rgba(0, 0, 0, 0.12), 9px 0 28px 8px rgba(0, 0, 0, 0.05)",
        "ksd-shadow-right":
          "-6px 0 16px 0 rgba(0, 0, 0, 0.08), -3px 0 6px -4px rgba(0, 0, 0, 0.12), -9px 0 28px 8px rgba(0, 0, 0, 0.05)",
        "ksd-shadow-top":
          "0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)",
      },
      border: {
        "ksd-border-radius-xs": "2px",
        "ksd-border-radius-sm": "4px",
        "ksd-border-radius": "6px",
        "ksd-border-radius-lg": "8px",
        "ksd-border-radius-outer": "4px",
        "ksd-line-type": "solid",
        "ksd-line-width": "1px",
        "ksd-outline-type": "solid",
        "ksd-outline-width": "3px",
      },
      padding: {
        "ksd-padding-xxs": "4px",
        "ksd-padding-xs": "8px",
        "ksd-padding-sm": "12px",
        "ksd-padding": "16px",
        "ksd-padding-md": "20px",
        "ksd-padding-lg": "24px",
        "ksd-padding-xl": "32px",
      },
      margin: {
        "ksd-margin-xxs": "4px",
        "ksd-margin-xs": "8px",
        "ksd-margin-sm": "12px",
        "ksd-margin": "16px",
        "ksd-margin-md": "20px",
        "ksd-margin-lg": "24px",
        "ksd-margin-xl": "32px",
        "ksd-margin-xxl": "48px",
      },
      font: {
        "ksd-font-family": "Nunito",
        "ksd-font-weight": "400",
        "ksd-font-weight-strong": "600",
        "ksd-line-height": "1.5",
        "ksd-line-height-lg": "1.5",
        "ksd-line-height-sm": "1.6666666666666667",
        "ksd-font-size-sm": "12px",
        "ksd-font-size": "14px",
        "ksd-font-size-lg": "16px",
        "ksd-font-size-xl": "20px",
      },
      other: {
        "ksd-popup-z-index": "110",
        "ksd-opacity-loading": "0.65",
        "ksd-tooltip-z-index": "170",
      },
      colors: {
        "ksd-bg-color": "#141414",
        "ksd-bg-container-color": "#141414",
        "ksd-bg-sidebar-color": "#141414",
        "ksd-bg-header-color": "#141414",
        "ksd-bg-popper-color": "#1f1f1f",
        "ksd-bg-notice-color": "#1f1f1f",
        "ksd-bg-modal-color": "#1f1f1f",
        "ksd-bg-tooltip-color": "#424242",
        "ksd-bg-mask-color": "rgba(0,0,0,0.45)",
        "ksd-bg-fill-color": "rgba(255,255,255,0.08)",
        "ksd-bg-fill-hover-color": "rgba(255,255,255,0.12)",
        "ksd-bg-disabled-color": "rgba(255,255,255,0.08)",
        "ksd-bg-hover-color": "rgba(255,255,255,0.08)",
        "ksd-bg-active-color": "rgba(255,255,255,0.18)",
        "ksd-text-main-color": "rgba(255,255,255,0.85)",
        "ksd-text-main-disabled-color": "rgba(255,255,255,0.25)",
        "ksd-text-main-hover-color": "",
        "ksd-text-secondary-color": "rgba(255, 255, 255, 0.65)",
        "ksd-text-secondary-disabled-color": "rga(255, 255, 255, 0.25)",
        "ksd-text-secondary-hover-color": "",
        "ksd-text-tertiary-color": "rgba(255, 255, 255, 0.45)",
        "ksd-text-quaternary-color": "rgba(255, 255, 255, 0.25)",
        "ksd-text-reverse-color": "#ffffff",
        "ksd-text-reverse-secondary-color": "",
        "ksd-text-placeholder-color": "rgba(255, 255, 255, 0.25)",
        "ksd-border-color": "#424242",
        "ksd-border-disabled-color": "#424242",
        "ksd-border-hover-color": "",
        "ksd-divider-color": "rgba(253,253,253,0.12)",
        "ksd-icon-color": "rgba(255,255,255,0.45)",
        "ksd-icon-hover-color": "rgba(255,255,255,0.85)",
        "ksd-outline-color": "#15325b",
        "ksd-accent-color": "#1668dc",
        "ksd-accent-hover-color": "#3c89e8",
        "ksd-accent-active-color": "#1554ad",
        "ksd-accent-bg-color": "#15325b",
        "ksd-accent-bg-hover-color": "#15417e",
        "ksd-accent-border-color": "#15325b",
        "ksd-accent-border-hover-color": "#15417e",
        "ksd-error-color": "#dc4446",
        "ksd-error-active-color": "#ad393a",
        "ksd-error-hover-color": "#e86e6b",
        "ksd-error-bg-color": "#2c1618",
        "ksd-error-bg-active-color": "#5b2526",
        "ksd-error-bg-hover-color": "#451d1f",
        "ksd-error-border-color": "#5b2526",
        "ksd-error-border-hover-color": "#7e2e2f",
        "ksd-warning-color": "#d89614",
        "ksd-warning-active-color": "#aa7714",
        "ksd-warning-hover-color": "#e8b339",
        "ksd-warning-bg-color": "#2b2111",
        "ksd-warning-bg-active-color": "",
        "ksd-warning-bg-hover-color": "#443111",
        "ksd-warning-border-color": "#594214",
        "ksd-warning-border-hover-color": "#7c5914",
        "ksd-success-color": "#49aa19",
        "ksd-success-active-color": "#3c8618",
        "ksd-success-hover-color": "#6abe39",
        "ksd-success-bg-color": "#162312",
        "ksd-success-bg-active-color": "",
        "ksd-success-bg-hover-color": "#1d3712",
        "ksd-success-border-color": "#274916",
        "ksd-success-border-hover-color": "#306317",
        "ksd-info-color": "#1668dc",
        "ksd-info-active-color": "#1554ad",
        "ksd-info-hover-color": "#3c89e8",
        "ksd-info-bg-color": "#111a2c",
        "ksd-info-bg-active-color": "",
        "ksd-info-bg-hover-color": "#112545",
        "ksd-info-border-color": "#15325b",
        "ksd-info-border-hover-color": "#15417e",
      },
    },
    components: {
      collapse: {
        "ksd-collapse-header-bg": "rgba(255,255,255,0.04)",
        "ksd-collapse-body-bg": "var(--ksd-bg-container-color)",
      },
      divider: {
        "ksd-divider-width": "1px",
      },
      button: {
        "ksd-button-bg": "var(--ksd-bg-color)",
        "ksd-button-border": "var(--ksd-border-color)",
        "ksd-button-padding": "15px",
        "ksd-button-padding-lg": "15px",
        "ksd-button-padding-sm": "7px",
        "ksd-button-bg-disabled-color": "var(--ksd-bg-disabled-color)",
        "ksd-button-border-disabled-color": "var(--ksd-border-disabled-color)",
        "ksd-button-text-disabled-color": "var(--ksd-text-main-disabled-color)",
      },
      input: {
        "ksd-input-padding-block": "4px",
        "ksd-input-padding-inline": "11px",
        "ksd-input-padding-block-sm": "0px",
        "ksd-input-padding-inline-sm": "7px",
        "ksd-input-padding-block-lg": "7px",
        "ksd-input-padding-inline-lg": "11px",
        "ksd-input-active-shadow": "0 0 0 2px rgba(23,117,249,0.31)",
      },
      radio: {
        "ksd-radio-dot-size": 6,
        "ksd-radio-size": 16,
        "ksd-radio-dot-color": "#ffffff",
        "ksd-radio-button-padding-inline": "15px",
      },
      slider: {
        "ksd-slider-control-size": "10px",
        "ksd-slider-rail-size": "4px",
        "ksd-slider-handle-size": "10px",
        "ksd-slider-handle-size-hover": "12px",
        "ksd-slider-handle-line-width": "2px",
        "ksd-slider-handle-line-width-hover": "2.5px",
        "ksd-slider-rail-bg": "var(--ksd-bg-fill-color)",
        "ksd-slider-rail-hover-bg": "var(--ksd-bg-fill-hover-color)",
        "ksd-slider-track-bg": "var(--ksd-accent-border-color)",
        "ksd-slider-track-hover-bg": "var(--ksd-accent-border-hover-color)",
        "ksd-slider-handle-color": "var(--ksd-accent-border-color)",
        "ksd-slider-handle-active-color": "var(--ksd-accent-color)",
        "ksd-slider-handle-active-outline-color": "rgba(22, 104, 220, 0.2)",
        "ksd-slider-handle-color-disabled": "#4f4f4f",
        "ksd-slider-track-bg-disabled": "var(--ksd-bg-disabled-color)",
      },
      switch: {
        "ksd-switch-track-height": "20px",
        "ksd-switch-track-height-sm": "16px",
        "ksd-switch-track-min-width": "40px",
        "ksd-switch-track-min-width-sm": "28px",
        "ksd-switch-track-padding": "2px",
        "ksd-switch-handle-bg": "#fff",
        "ksd-switch-handle-size": "16px",
        "ksd-switch-handle-size-sm": "12px",
        "ksd-switch-handle-shadow": "0 2px 4px 0 rgba(0, 35, 11, 0.2)",
        "ksd-switch-inner-min-margin": "9px",
        "ksd-switch-inner-max-margin": "24px",
        "ksd-switch-inner-min-margin-sm": "6px",
        "ksd-switch-inner-max-margin-sm": "18px",
        "ksd-switch-bg-unchecked-color": "var(--ksd-text-quaternary-color)",
        "ksd-switch-bg-unchecked-hover-color": "var(--ksd-text-tertiary-color)",
        "ksd-switch-checked-color": "#ffffff",
        "ksd-switch-unchecked-color": "#ffffff",
      },
      popper: {
        "ksd-popper-inner-padding": "12px",
        "ksd-popper-z-index": "110",
      },
      dropdown: {
        "ksd-dropdown-inner-padding": "5px 12px",
        "ksd-dropdown-inner-padding-lg": "12px",
        "ksd-dropdown-inner-min-width-lg": "150px",
        "ksd-dropdown-bg-item-color": "var(--ksd-bg-hover-color)",
        "ksd-dropdown-z-index": "120",
      },
      select: {
        "ksd-select-internal_fixed_item_margin": "2px",
        "ksd-select-z-index": "140",
        "ksd-select-option-selected-color": "var(--ksd-text-main-color)",
        "ksd-select-option-selected-font-weight": "var(--ksd-font-weight-strong)",
        "ksd-select-option-selected-bg": "var(--ksd-accent-bg-color)",
        "ksd-select-option-active-bg": "var(--ksd-bg-hover-color)",
        "ksd-select-option-padding": "5px 12px",
        "ksd-select-option-font-size": "var(--ksd-font-size)",
        "ksd-select-option-line-height": "var(--ksd-line-height)",
        "ksd-select-option-height": "var(--ksd-control-height)",
        "ksd-select-single-item-height-lg": "var(--ksd-control-height-lg)",
        "ksd-select-multiple-item-bg": "rgba(255, 255, 255, 0.12)",
        "ksd-select-multiple-item-border-color": "transparent",
        "ksd-select-multiple-item-height": "24px",
        "ksd-select-multiple-item-height-sm": "16px",
        "ksd-select-multiple-item-height-lg": "32px",
        "ksd-select-show-arrow-padding-inline-end": "18px",
        "ksd-select-selector-padding-sm": "8px",
      },
      popconfirm: {
        "ksd-pop-confirm-inner-padding": "12px",
        "ksd-pop-confirm-z-index": "130",
      },
      message: {
        "ksd-message-z-index": "160",
        "ksd-message-content-bg": "var(--ksd-bg-notice-color)",
        "ksd-message-content-padding": "9px 12px",
      },
      notification: {
        "ksd-notification-z-index": "150",
        "ksd-notification-width": "384px",
        "ksd-notification-block-margin": "24px",
        "ksd-notification-inline-margin": "24px",
        "ksd-notification-blur-bg-color": "rgba(255,255,255,0.04)",
      },
      modal: {
        "ksd-modal-footer-bg": "transparent",
        "ksd-modal-header-bg": "var(--ksd-bg-modal-color)",
        "ksd-modal-title-line-height": "1.5",
        "ksd-modal-title-font-size": "16px",
        "ksd-modal-content-bg": "var(--ksd-bg-modal-color)",
        "ksd-modal-title-color": "var(--ksd-text-main-color)",
        "ksd-modal-content-padding": "20px 24px",
        "ksd-modal-header-padding": "0px",
        "ksd-modal-header-border-bottom": "none",
        "ksd-modal-header-margin-bottom": "8px",
        "ksd-modal-body-padding": "0px",
        "ksd-modal-footer-padding": "0px",
        "ksd-modal-footer-border-top": "none",
        "ksd-modal-footer-border-radius": "0px",
        "ksd-modal-footer-margin-top": "12px",
        "ksd-modal-margin-block": "100px",
        "ksd-modal-z-index": "100",
      },
      tag: {
        "ksd-tag-bg-color-magenta": "#291321",
        "ksd-tag-text-color-magenta": "#e0529c",
        "ksd-tag-border-color-magenta": "#551c3b",
        "ksd-tag-bg-color-red": "#2a1215",
        "ksd-tag-text-color-red": "#e84749",
        "ksd-tag-border-color-red": "#58181c",
        "ksd-tag-bg-color-volcano": "#2b1611",
        "ksd-tag-text-color-volcano": "#e87040",
        "ksd-tag-border-color-volcano": "#592716",
        "ksd-tag-bg-color-orange": "#2b1d11",
        "ksd-tag-text-color-orange": "#e89a3c",
        "ksd-tag-border-color-orange": "#593815",
        "ksd-tag-bg-color-gold": "#2b2111",
        "ksd-tag-text-color-gold": "#e8b339",
        "ksd-tag-border-color-gold": "#594214",
        "ksd-tag-bg-color-lime": "#1f2611",
        "ksd-tag-text-color-lime": "#a9d134",
        "ksd-tag-border-color-lime": "#3e4f13",
        "ksd-tag-bg-color-green": "#162312",
        "ksd-tag-text-color-green": "#6abe39",
        "ksd-tag-border-color-green": "#274916",
        "ksd-tag-bg-color-cyan": "#112123",
        "ksd-tag-text-color-cyan": "#33bcb7",
        "ksd-tag-border-color-cyan": "#144848",
        "ksd-tag-bg-color-blue": "#111a2c",
        "ksd-tag-text-color-blue": "#3c89e8",
        "ksd-tag-border-color-blue": "#15325b",
        "ksd-tag-bg-color-geekblue": "#131629",
        "ksd-tag-text-color-geekblue": "#5273e0",
        "ksd-tag-border-color-geekblue": "#1c2755",
        "ksd-tag-bg-color-purple": "#1a1325",
        "ksd-tag-text-color-purple": "#854eca",
        "ksd-tag-border-color-purple": "#301c4d",
        "ksd-tag-bg-color-success": "var(--ksd-success-bg-color)",
        "ksd-tag-text-color-success": "var(--ksd-success-color)",
        "ksd-tag-border-color-success": "var(--ksd-success-border-color)",
        "ksd-tag-bg-color-processing": "var(--ksd-info-bg-color)",
        "ksd-tag-text-color-processing": "var(--ksd-info-color)",
        "ksd-tag-border-color-processing": "var(--ksd-info-border-color)",
        "ksd-tag-bg-color-error": "var(--ksd-error-bg-color)",
        "ksd-tag-text-color-error": "var(--ksd-error-color)",
        "ksd-tag-border-color-error": "var(--ksd-error-border-color)",
        "ksd-tag-bg-color-warning": "var(--ksd-warning-bg-color)",
        "ksd-tag-text-color-warning": "var(--ksd-warning-color)",
        "ksd-tag-border-color-warning": "var(--ksd-warning-border-color)",
        "ksd-tag-default-color": "var(--ksd-text-main-color)",
        "ksd-tag-default-bg": "#1d1d1d",
      },
      skeleton: {
        "ksd-skeleton-gradient-from-color": "rgba(255, 255, 255, 0.12)",
        "ksd-skeleton-gradient-to-color": "rgba(255, 255, 255, 0.18)",
        "ksd-skeleton-title-height": "16px",
        "ksd-skeleton-block-radius": "4px",
      },
    },
  },
};
