import type { ThemeName, ThemeVariableConfig } from "../types";

export const THEME_COLORS: Record<ThemeName, ThemeVariableConfig> = {
  light: {
    common: {
      transition: {
        "ksd-transition-fast": "0.1s",
        "ksd-transition-mid": "0.2s",
        "ksd-transition-slow": "0.3s",
      },
      controlHeight: {
        "ksd-control-height-sm": "24px",
        "ksd-control-height": "32px",
        "ksd-control-height-lg": "40px",
        "ksd-control-interactive-size": "16px",
      },

      shadow: {
        "ksd-shadow":
          "0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)",
        "ksd-shadow-secondary":
          "0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)",
        "ksd-shadow-tertiary":
          "0 1px 2px 0 rgba(0, 0, 0, 0.03), 0 1px 6px -1px rgba(0, 0, 0, 0.02), 0 2px 4px 0 rgba(0, 0, 0, 0.02)",
        "ksd-shadow-accent":
          "0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)",
        "ksd-shadow-bottom":
          "0 -6px 16px 0 rgba(0, 0, 0, 0.08), 0 -3px 6px -4px rgba(0, 0, 0, 0.12), 0 -9px 28px 8px rgba(0, 0, 0, 0.05)",
        "ksd-shadow-left":
          "6px 0 16px 0 rgba(0, 0, 0, 0.08), 3px 0 6px -4px rgba(0, 0, 0, 0.12), 9px 0 28px 8px rgba(0, 0, 0, 0.05)",
        "ksd-shadow-right":
          "-6px 0 16px 0 rgba(0, 0, 0, 0.08), -3px 0 6px -4px rgba(0, 0, 0, 0.12), -9px 0 28px 8px rgba(0, 0, 0, 0.05)",
        "ksd-shadow-top":
          "0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)",
      },
      border: {
        "ksd-border-radius-xs": "2px",
        "ksd-border-radius-sm": "4px",
        "ksd-border-radius": "6px",
        "ksd-border-radius-lg": "8px",
        "ksd-border-radius-outer": "4px",
      },
      padding: {
        "ksd-padding-xxs": "4px",
        "ksd-padding-xs": "8px",
        "ksd-padding-sm": "12px",
        "ksd-padding": "16px",
        "ksd-padding-md": "20px",
        "ksd-padding-lg": "24px",
        "ksd-padding-xl": "32px",
      },
      margin: {
        "ksd-margin-xxs": "4px",
        "ksd-margin-xs": "8px",
        "ksd-margin-sm": "12px",
        "ksd-margin": "16px",
        "ksd-margin-md": "20px",
        "ksd-margin-lg": "24px",
        "ksd-margin-xl": "32px",
        "ksd-margin-xxl": "48px",
      },
      font: {
        "ksd-font-family": "Nunito",
        "ksd-font-weight": "400",
        "ksd-line-height": "1.5",
        "ksd-font-size-sm": "12px",
        "ksd-font-size-lg": "16px",
        "ksd-font-size-xl": "20px",
      },
      colors: {
        "ksd-bg-color": "#edeef0",
        "ksd-bg-container-color": "#ffffff",
        "ksd-bg-sidebar-color": "#edeef0",
        "ksd-bg-header-color": "#edeef0",
        "ksd-bg-modal-color": "#ffffff",
        "ksd-bg-mask-color": "rgba(0,0,0,0.45)",
        "ksd-bg-fill-color": "rgba(0,0,0,0.04)",
        "ksd-bg-fill-hover-color": "rgba(0,0,0,0.06)",
        "ksd-bg-disabled-color": "rgba(0, 0, 0, 0.04)",
        "ksd-bg-hover-color": "rgba(0, 0, 0, 0.06)",
        "ksd-bg-active-color": "rgba(0, 0, 0, 0.15)",
        "ksd-text-main-color": "#262626",
        "ksd-text-main-disabled-color": "rgba(0, 0, 0, 0.25)",
        "ksd-text-main-hover-color": "",
        "ksd-text-secondary-color": "#8c8c8c",
        "ksd-text-secondary-disabled-color": "rga(140, 140, 140, 0.25)",
        "ksd-text-secondary-hover-color": "",
        "ksd-text-reverse-color": "#ffffff",
        "ksd-text-reverse-secondary-color": "",
        "ksd-text-placeholder-color": "rgba(0, 0, 0, 0.25)",
        "ksd-border-color": "#d9d9d9",
        "ksd-border-hover-color": "",
        "ksd-border-split-color": "rgba(5,5,5,0.06)",
        "ksd-icon-color": "rgba(0, 0, 0, 0.45)",
        "ksd-icon-hover-color": "#262626",
        "ksd-outline-color": "#91caff",
        "ksd-accent-color": "#1677ff",
        "ksd-accent-hover-color": "#4096ff",
        "ksd-accent-active-color": "#0958d9",
        "ksd-accent-bg-color": "#e6f4ff",
        "ksd-accent-bg-hover-color": "#bae0ff",
        "ksd-error-color": "#ff4d4f",
        "ksd-error-active-color": "#d9363e",
        "ksd-error-hover-color": "#ff7875",
        "ksd-error-bg-color": "#fff2f0",
        "ksd-error-bg-active-color": "#ffccc7",
        "ksd-error-bg-hover-color": "#fff1f0",
        "ksd-warning-color": "#faad14",
        "ksd-warning-active-color": "#d48806",
        "ksd-warning-hover-color": "#ffc53d",
        "ksd-warning-bg-color": "#fffbe6",
        "ksd-warning-bg-active-color": "",
        "ksd-warning-bg-hover-color": "#fff1b8",
        "ksd-success-color": "#52c41a",
        "ksd-success-active-color": "#389e0d",
        "ksd-success-hover-color": "#73d13d",
        "ksd-success-bg-color": "#f6ffed",
        "ksd-success-bg-active-color": "",
        "ksd-success-bg-hover-color": "#d9f7be",
        "ksd-info-color": "#1677ff",
        "ksd-info-active-color": "#0958d9",
        "ksd-info-hover-color": "#69b1ff",
        "ksd-info-bg-color": "#e6f4ff",
        "ksd-info-bg-active-color": "",
        "ksd-info-bg-hover-color": "#bae0ff",
      },
    },
    components: {
      collapse: {
        "ksd-collapse-header-bg": "rgba(0, 0, 0, 0.02)",
        "ksd-collapse-body-bg": "#ffffff",
      },
      divider: {
        "ksd-divider-color": "rgba(5,5,5,0.06)",
        "ksd-divider-width": "1px",
      },
      button: {
        "ksd-button-bg": "#ffffff",
        "ksd-button-border": "#d9d9d9",
        "ksd-button-padding": "15px",
        "ksd-button-padding-lg": "15px",
        "ksd-button-padding-sm": "7px",
        "ksd-button-bg-disabled-color": "rgba(0, 0, 0, 0.04)",
        "ksd-button-border-disabled-color": "#d9d9d9",
        "ksd-button-text-disabled-color": "rgba(0, 0, 0, 0.25)",
      },
      input: {
        "ksd-input-padding-block": "4px",
        "ksd-input-padding-inline": "11px",
        "ksd-input-padding-block-sm": "0px",
        "ksd-input-padding-inline-sm": "7px",
        "ksd-input-padding-block-lg": "7px",
        "ksd-input-padding-inline-lg": "11px",
        "ksd-input-active-shadow": "0 0 0 2px rgba(5,145,255,0.1)",
      },
      radio: {
        "ksd-radio-dot-size": 6,
        "ksd-radio-size": 16,
        "ksd-radio-dot-color": "#ffffff",
      },
    },
  },
};
