export * from "./preferences.types";

export type CloseByClickOutsideEvent = "mousedown" | "pointerdown";
export type GlobalEmits = {
  click: [event: HTMLElementEventMap["click"]];
  dblclick: [event: HTMLElementEventMap["dblclick"]];
  contextmenu: [event: HTMLElementEventMap["contextmenu"]];
  mousedown: [event: HTMLElementEventMap["mousedown"]];
  mouseenter: [event: HTMLElementEventMap["mouseenter"]];
  mouseleave: [event: HTMLElementEventMap["mouseleave"]];
  mousemove: [event: HTMLElementEventMap["mousemove"]];
  mouseout: [event: HTMLElementEventMap["mouseout"]];
  mouseover: [event: HTMLElementEventMap["mouseover"]];
  mouseup: [event: HTMLElementEventMap["mouseup"]];
  keydown: [event: HTMLElementEventMap["keydown"]];
  keypress: [event: HTMLElementEventMap["keypress"]];
  keyup: [event: HTMLElementEventMap["keyup"]];
  blur: [event: HTMLElementEventMap["blur"]];
  focus: [event: HTMLElementEventMap["focus"]];
  change: [event: HTMLElementEventMap["change"]];
  input: [event: HTMLElementEventMap["input"]];
  wheel: [event: HTMLElementEventMap["wheel"]];
  touchstart: [event: HTMLElementEventMap["touchstart"]];
  touchcancel: [event: HTMLElementEventMap["touchcancel"]];
  touchend: [event: HTMLElementEventMap["touchend"]];
  touchmove: [event: HTMLElementEventMap["touchmove"]];
  copy: [event: HTMLElementEventMap["copy"]];
  cut: [event: HTMLElementEventMap["cut"]];
  pointerdown: [event: HTMLElementEventMap["pointerdown"]];
  pointerenter: [event: HTMLElementEventMap["pointerenter"]];
  pointerleave: [event: HTMLElementEventMap["pointerleave"]];
  pointercancel: [event: HTMLElementEventMap["pointercancel"]];
  pointermove: [event: HTMLElementEventMap["pointermove"]];
  pointerout: [event: HTMLElementEventMap["pointerout"]];
  pointerover: [event: HTMLElementEventMap["pointerover"]];
  pointerup: [event: HTMLElementEventMap["pointerup"]];
  scroll: [event: HTMLElementEventMap["scroll"]];
  resize: [event: HTMLElementEventMap["resize"]];
};
