import type { Config } from "prettier";

export const recommended: Config = {
  printWidth: 100,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  trailingComma: "all",
  bracketSpacing: true,
  arrowParens: "always",
  plugins: ["@trivago/prettier-plugin-sort-imports"],
  importOrder: [
    "@krainovsd/fastify-trace/trace",
    "<THIRD_PARTY_MODULES>",
    "^@/app",
    "^@/app/(.*)$",
    "^@/pages/(.*)$",
    "^@/widgets/(.*)$",
    "^@/features/(.*)$",
    "^@/entities/(.*)$",
    "^@/shared/(.*)$",
    "^@/templates/(.*)$",
    "^@/organisms/(.*)$",
    "^@/molecules/(.*)$",
    "^@/atoms/(.*)$",
    "^@/(.*)$",
    "^[./]",
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
};
