import {
  FORCE_SETTINGS,
  GRAPH_SETTINGS,
  LINK_OPTIONS,
  NODE_OPTIONS,
} from "@/module/GraphCanvas/constants";
import type {
  ForceSettingsInterface,
  GraphSettingsInterface,
  LinkOptionsInterface,
  NodeOptionsInterface,
} from "../module/GraphCanvas";
import type { GraphSettingsInputInterface } from "../types/controls";

export function getForceControls<
  NodeData extends Record<string, unknown>,
  LinkData extends Record<string, unknown>,
>(keys?: (keyof ForceSettingsInterface<NodeData, LinkData>)[]) {
  const FORCE_CONTROLS: GraphSettingsInputInterface<
    keyof ForceSettingsInterface<NodeData, LinkData>
  >[] = [
    {
      id: "centerStrength",
      initialValue: FORCE_SETTINGS.centerStrength,
      label: "Граница центра",
      max: 1,
      min: 0,
      step: 0.01,
      type: "range",
    },
    {
      id: "collideStrength",
      initialValue: FORCE_SETTINGS.collideStrength,
      label: "Сила отталкивания",
      max: 1,
      min: 0,
      step: 0.01,
      type: "range",
    },
    {
      id: "collideAdditionalRadius",
      initialValue: FORCE_SETTINGS.collideAdditionalRadius,
      label: "Радиус отталкивания",
      max: 300,
      min: 0,
      step: 0.1,
      type: "range",
    },
    {
      id: "collideIterations",
      initialValue: FORCE_SETTINGS.collideIterations,
      label: "Итерации отталкивания",
      max: 10,
      min: 0,
      step: 1,
      type: "range",
    },
    {
      id: "chargeStrength",
      initialValue:
        typeof FORCE_SETTINGS.chargeStrength === "number" ? FORCE_SETTINGS.chargeStrength : 0,
      label: "Гравитация",
      max: 0,
      min: -300,
      step: 0.1,
      type: "range",
    },
    {
      type: "range",
      id: "xForce",
      min: 0,
      max: 1,
      step: 0.01,
      label: "Граница X",
      initialValue: typeof FORCE_SETTINGS.xForce === "number" ? FORCE_SETTINGS.xForce : 0,
    },
    {
      type: "range",
      id: "yForce",
      min: 0,
      max: 1,
      step: 0.01,
      label: "Граница Y",
      initialValue: typeof FORCE_SETTINGS.yForce === "number" ? FORCE_SETTINGS.yForce : 0,
    },
    {
      type: "range",
      id: "xStrength",
      min: 0,
      max: 1,
      step: 0.01,
      label: "Гравитация X",
      initialValue: typeof FORCE_SETTINGS.xStrength === "number" ? FORCE_SETTINGS.xStrength : 0,
    },
    {
      type: "range",
      id: "yStrength",
      min: 0,
      max: 1,
      step: 0.01,
      label: "Гравитация Y",
      initialValue: typeof FORCE_SETTINGS.yStrength === "number" ? FORCE_SETTINGS.yStrength : 0,
    },
    {
      type: "range",
      id: "linkStrength",
      min: 0,
      max: 1,
      step: 0.01,
      label: "Натяжение связей",
      initialValue:
        typeof FORCE_SETTINGS.linkStrength === "number" ? FORCE_SETTINGS.linkStrength : 0,
    },
    {
      type: "range",
      id: "linkDistance",
      min: 0,
      max: 300,
      step: 0.1,
      label: "Расстояние связей",
      initialValue:
        typeof FORCE_SETTINGS.linkDistance === "number" ? FORCE_SETTINGS.linkDistance : 30,
    },
    {
      id: "collideOn",
      type: "checkbox",
      initialValue: FORCE_SETTINGS.collideOn,
      label: "Отталкивание",
    },
  ];

  return keys ? FORCE_CONTROLS.filter((control) => keys.includes(control.id)) : FORCE_CONTROLS;
}

export function getGraphControls<NodeData extends Record<string, unknown>>(
  keys?: (keyof GraphSettingsInterface<NodeData>)[],
) {
  const GRAPH_CONTROLS: GraphSettingsInputInterface<keyof GraphSettingsInterface<NodeData>>[] = [
    {
      id: "highlightByNodeNodeSizingAdditional",
      initialValue: GRAPH_SETTINGS.highlightByNodeNodeSizingAdditional,
      max: 10,
      min: 0.1,
      step: 0.01,
      type: "range",
      label: "Дополнительный размер при анимации ноды",
    },
    {
      id: "highlightByNodeNodeColorFadingMin",
      initialValue: GRAPH_SETTINGS.highlightByNodeNodeColorFadingMin,
      max: 1,
      min: 0.01,
      step: 0.01,
      type: "range",
      label: "Граница затухания цвета при анимации ноды",
    },
    {
      id: "highlightByNodeTextShiftXAdditional",
      initialValue: GRAPH_SETTINGS.highlightByNodeTextShiftXAdditional,
      max: 50,
      min: 0,
      step: 0.1,
      type: "range",
      label: "Смещение текста по X при анимации ноды",
    },
    {
      id: "highlightByNodeTextShiftYAdditional",
      initialValue: GRAPH_SETTINGS.highlightByNodeTextShiftYAdditional,
      max: 50,
      min: 0,
      step: 0.1,
      type: "range",
      label: "Смещение текста по Y при анимации ноды",
    },
    {
      id: "highlightByNodeTextSizingAdditional",
      initialValue: GRAPH_SETTINGS.highlightByNodeTextSizingAdditional,
      max: 10,
      min: 0.1,
      step: 0.1,
      type: "range",
      label: "Увеличение текста при анимации ноды",
    },
    {
      id: "highlightByNodeTextWeightAdditional",
      initialValue: GRAPH_SETTINGS.highlightByNodeTextWeightAdditional,
      max: 1000,
      min: 0,
      step: 100,
      type: "range",
      label: "Увеличение жирности текста при анимации ноды",
    },
    {
      id: "highlightByNodeTextWidthAdditional",
      initialValue: GRAPH_SETTINGS.highlightByNodeTextWidthAdditional,
      max: 100,
      min: 0,
      step: 0.1,
      type: "range",
      label: "Увеличение ширины текста при анимации ноды",
    },
    {
      id: "highlightByNodeTextFadingMin",
      initialValue: GRAPH_SETTINGS.highlightByNodeTextFadingMin,
      max: 1,
      min: 0,
      step: 0.01,
      type: "range",
      label: "Граница затухания текста при анимации ноды",
    },
    {
      id: "highlightByNodeLinkFadingMin",
      initialValue: GRAPH_SETTINGS.highlightByNodeLinkFadingMin,
      max: 1,
      min: 0,
      step: 0.01,
      type: "range",
      label: "Граница затухания связи при анимации ноды",
    },
    {
      id: "highlightByNodeNodeFadingMin",
      initialValue: GRAPH_SETTINGS.highlightByNodeNodeFadingMin,
      max: 1,
      min: 0,
      step: 0.01,
      type: "range",
      label: "Граница затухания ноды при анимации ноды",
    },
    {
      id: "highlightByNodeArrowFadingMin",
      initialValue: GRAPH_SETTINGS.highlightByNodeArrowFadingMin,
      max: 1,
      min: 0,
      step: 0.01,
      type: "range",
      label: "Граница затухания стрелки при анимации ноды",
    },
    {
      id: "highlightByNodeOnlyRoot",
      type: "checkbox",
      initialValue: GRAPH_SETTINGS.highlightByNodeOnlyRoot,
      label: "Дополнительная анимация только главное цели при анимации ноды",
    },

    {
      id: "highlightByLinkNodeSizingAdditional",
      initialValue: GRAPH_SETTINGS.highlightByLinkNodeSizingAdditional,
      max: 10,
      min: 0.1,
      step: 0.01,
      type: "range",
      label: "Дополнительный размер при анимации связи",
    },
    {
      id: "highlightByLinkNodeColorFadingMin",
      initialValue: GRAPH_SETTINGS.highlightByLinkNodeColorFadingMin,
      max: 1,
      min: 0.01,
      step: 0.01,
      type: "range",
      label: "Граница затухания цвета при анимации связи",
    },
    {
      id: "highlightByLinkTextShiftXAdditional",
      initialValue: GRAPH_SETTINGS.highlightByLinkTextShiftXAdditional,
      max: 50,
      min: 0,
      step: 0.1,
      type: "range",
      label: "Смещение текста по X при анимации связи",
    },
    {
      id: "highlightByLinkTextShiftYAdditional",
      initialValue: GRAPH_SETTINGS.highlightByLinkTextShiftYAdditional,
      max: 50,
      min: 0,
      step: 0.1,
      type: "range",
      label: "Смещение текста по Y при анимации связи",
    },
    {
      id: "highlightByLinkTextSizingAdditional",
      initialValue: GRAPH_SETTINGS.highlightByLinkTextSizingAdditional,
      max: 10,
      min: 0.1,
      step: 0.1,
      type: "range",
      label: "Увеличение текста при анимации связи",
    },
    {
      id: "highlightByLinkTextWeightAdditional",
      initialValue: GRAPH_SETTINGS.highlightByLinkTextWeightAdditional,
      max: 1000,
      min: 0,
      step: 100,
      type: "range",
      label: "Увеличение жирности текста при анимации связи",
    },
    {
      id: "highlightByLinkTextWidthAdditional",
      initialValue: GRAPH_SETTINGS.highlightByLinkTextWidthAdditional,
      max: 100,
      min: 0,
      step: 0.1,
      type: "range",
      label: "Увеличение ширины текста при анимации связи",
    },
    {
      id: "highlightByLinkTextFadingMin",
      initialValue: GRAPH_SETTINGS.highlightByLinkTextFadingMin,
      max: 1,
      min: 0,
      step: 0.01,
      type: "range",
      label: "Граница затухания текста при анимации связи",
    },
    {
      id: "highlightByLinkLinkFadingMin",
      initialValue: GRAPH_SETTINGS.highlightByLinkLinkFadingMin,
      max: 1,
      min: 0,
      step: 0.01,
      type: "range",
      label: "Граница затухания связи при анимации связи",
    },
    {
      id: "highlightByLinkNodeFadingMin",
      initialValue: GRAPH_SETTINGS.highlightByLinkNodeFadingMin,
      max: 1,
      min: 0,
      step: 0.01,
      type: "range",
      label: "Граница затухания ноды при анимации связи",
    },
    {
      id: "highlightByLinkArrowFadingMin",
      initialValue: GRAPH_SETTINGS.highlightByLinkArrowFadingMin,
      max: 1,
      min: 0,
      step: 0.01,
      type: "range",
      label: "Граница затухания стрелки при анимации связи",
    },
    {
      id: "highlightByLinkOnlyRoot",
      type: "checkbox",
      initialValue: GRAPH_SETTINGS.highlightByLinkOnlyRoot,
      label: "Дополнительная анимация только главное цели при анимации связи",
    },
    {
      id: "highlightDownStep",
      initialValue: GRAPH_SETTINGS.highlightDownStep,
      max: 1,
      min: 0.01,
      step: 0.01,
      type: "range",
      label: "Скорость отмены анимации",
    },
    {
      id: "highlightUpStep",
      initialValue: GRAPH_SETTINGS.highlightUpStep,
      max: 1,
      min: 0.01,
      step: 0.01,
      type: "range",
      label: "Скорость применения анимации",
    },
    {
      id: "nodeRadiusInitial",
      initialValue: GRAPH_SETTINGS.nodeRadiusInitial,
      max: 50,
      min: 0.1,
      step: 0.1,
      type: "range",
      label: "Изначальный радиус ноды",
    },
    {
      id: "nodeRadiusCoefficient",
      initialValue: GRAPH_SETTINGS.nodeRadiusCoefficient,
      max: 100,
      min: 0.1,
      step: 0.1,
      type: "range",
      label: "Количество связей для увеличения радиуса",
    },
    {
      id: "nodeRadiusFactor",
      initialValue: GRAPH_SETTINGS.nodeRadiusFactor,
      max: 50,
      min: 0.1,
      step: 0.1,
      type: "range",
      label: "Коэффициент увеличения радиуса",
    },

    {
      id: "stickAfterDrag",
      type: "checkbox",
      initialValue: GRAPH_SETTINGS.stickAfterDrag,
      label: "Фиксировании ноды после перетаскивания",
    },
    {
      id: "highlightByHoverNode",
      type: "checkbox",
      initialValue: GRAPH_SETTINGS.highlightByHoverNode,
      label: "Анимации при наведении",
    },
    {
      id: "nodeRadiusFlexible",
      type: "checkbox",
      initialValue: GRAPH_SETTINGS.nodeRadiusFlexible,
      label: "Гибкий радиус ноды",
    },
  ];

  return keys ? GRAPH_CONTROLS.filter((control) => keys.includes(control.id)) : GRAPH_CONTROLS;
}

export function getNodeControls<
  NodeData extends Record<string, unknown>,
  LinkData extends Record<string, unknown>,
>(keys?: (keyof NodeOptionsInterface<NodeData, LinkData>)[]) {
  const NODE_CONTROLS: GraphSettingsInputInterface<
    keyof NodeOptionsInterface<NodeData, LinkData>
  >[] = [
    {
      id: "alpha",
      type: "range",
      max: 1,
      min: 0,
      step: 0.1,
      label: "Прозрачность",
      initialValue: NODE_OPTIONS.alpha,
    },

    {
      id: "radius",
      type: "range",
      max: 50,
      min: 1,
      step: 1,
      label: "Радиус",
      initialValue: NODE_OPTIONS.radius,
    },
    {
      id: "borderWidth",
      type: "range",
      max: 5,
      min: 0,
      step: 0.1,
      label: "Толщина границы",
      initialValue: NODE_OPTIONS.borderWidth,
    },
    {
      id: "borderColor",
      type: "color",
      initialValue: "#000000FF",
      label: "Цвет границы",
    },
    {
      id: "color",
      type: "color",
      initialValue: "#000000FF",
      label: "Цвет",
    },
    {
      id: "textAlpha",
      type: "range",
      max: 1,
      min: 0,
      step: 0.1,
      label: "Прозрачность текста",
      initialValue: NODE_OPTIONS.textAlpha,
    },
    {
      id: "textWidth",
      type: "range",
      max: 200,
      min: 5,
      step: 1,
      label: "Ширина текста",
      initialValue: NODE_OPTIONS.textWidth,
    },
    {
      id: "textShiftX",
      type: "range",
      max: 100,
      min: 0,
      step: 0.1,
      label: "Смещение X текста",
      initialValue: NODE_OPTIONS.textShiftX,
    },
    {
      id: "textShiftY",
      type: "range",
      max: 100,
      min: 0,
      step: 0.1,
      label: "Смещение Y текста",
      initialValue: 4,
    },
    {
      id: "textWeight",
      type: "range",
      max: 1000,
      min: 100,
      step: 100,
      label: "Жирность текста",
      initialValue: NODE_OPTIONS.textWeight,
    },
    {
      id: "textGap",
      type: "range",
      max: 30,
      min: 0,
      step: 0.1,
      label: "Расстояние между строками",
      initialValue: NODE_OPTIONS.textGap,
    },
    {
      id: "highlightByNodeNodeFading",
      type: "checkbox",
      initialValue: NODE_OPTIONS.highlightByNodeNodeFading,
      label: "Затухание при анимации ноды",
    },
    {
      id: "highlightByNodeNodeColor",
      type: "checkbox",
      initialValue: NODE_OPTIONS.highlightByNodeNodeColor,
      label: "Затухание цвета при анимации ноды",
    },
    {
      id: "highlightByNodeNodeSizing",
      type: "checkbox",
      initialValue: NODE_OPTIONS.highlightByNodeNodeSizing,
      label: "Изменение размера при анимации ноды",
    },
    {
      id: "highlightByNodeTextFading",
      type: "checkbox",
      initialValue: NODE_OPTIONS.highlightByNodeTextFading,
      label: "Затухание текста при анимации ноды",
    },
    {
      id: "highlightByNodeTextSizing",
      type: "checkbox",
      initialValue: NODE_OPTIONS.highlightByNodeTextSizing,
      label: "Изменение размера текста при анимации ноды",
    },

    {
      id: "highlightByLinkNodeFading",
      type: "checkbox",
      initialValue: NODE_OPTIONS.highlightByLinkNodeFading,
      label: "Затухание при анимации связи",
    },
    {
      id: "highlightByLinkNodeColor",
      type: "checkbox",
      initialValue: NODE_OPTIONS.highlightByLinkNodeColor,
      label: "Затухание цвета при анимации связи",
    },
    {
      id: "highlightByLinkNodeSizing",
      type: "checkbox",
      initialValue: NODE_OPTIONS.highlightByLinkNodeSizing,
      label: "Изменение размера при анимации связи",
    },
    {
      id: "highlightByLinkTextFading",
      type: "checkbox",
      initialValue: NODE_OPTIONS.highlightByLinkTextFading,
      label: "Затухание текста при анимации связи",
    },
    {
      id: "highlightByLinkTextSizing",
      type: "checkbox",
      initialValue: NODE_OPTIONS.highlightByLinkTextSizing,
      label: "Изменение размера текста при анимации связи",
    },
  ];

  return keys ? NODE_CONTROLS.filter((control) => keys.includes(control.id)) : NODE_CONTROLS;
}

export function getLinkControls<
  NodeData extends Record<string, unknown>,
  LinkData extends Record<string, unknown>,
>(keys?: (keyof LinkOptionsInterface<NodeData, LinkData>)[]) {
  const LINK_CONTROLS: GraphSettingsInputInterface<
    keyof LinkOptionsInterface<NodeData, LinkData>
  >[] = [
    {
      id: "alpha",
      type: "range",
      max: 1,
      min: 0,
      step: 0.1,
      label: "Прозрачность",
      initialValue: LINK_OPTIONS.alpha,
    },
    {
      id: "width",
      type: "range",
      max: 10,
      min: 0.1,
      step: 0.1,
      label: "Толщина",
      initialValue: 0.1,
    },
    {
      id: "arrowAlpha",
      type: "range",
      max: 1,
      min: 0,
      step: 0.1,
      label: "Прозрачность стрелки",
      initialValue: LINK_OPTIONS.arrowAlpha,
    },
    {
      id: "arrowSize",
      type: "range",
      max: 10,
      min: 0.1,
      step: 0.1,
      label: "Размер стрелки",
      initialValue: LINK_OPTIONS.arrowSize,
    },
    {
      id: "particleAlpha",
      type: "range",
      max: 1,
      min: 0,
      step: 0.1,
      label: "Прозрачность частиц",
      initialValue: LINK_OPTIONS.particleAlpha,
    },
    {
      id: "particleRadius",
      type: "range",
      max: 10,
      min: 0.1,
      step: 0.1,
      label: "Радиус частиц",
      initialValue: LINK_OPTIONS.particleRadius,
    },
    {
      id: "particleCount",
      type: "range",
      max: 20,
      min: 1,
      step: 1,
      label: "Количество частиц",
      initialValue: LINK_OPTIONS.particleCount,
    },
    {
      id: "particleSteps",
      type: "range",
      max: 200,
      min: 1,
      step: 1,
      label: "Количество кадров у частиц",
      initialValue: LINK_OPTIONS.particleSteps,
    },
    {
      id: "color",
      type: "color",
      initialValue: "#000000FF",
      label: "Цвет",
    },
    {
      id: "arrowColor",
      type: "color",
      initialValue: "#000000FF",
      label: "Цвет стрелки",
    },
    {
      id: "particleColor",
      type: "color",
      initialValue: "#000000FF",
      label: "Цвет частиц",
    },
    {
      id: "pretty",
      type: "checkbox",
      label: "Обсчет соединения",
      initialValue: LINK_OPTIONS.pretty,
    },
    {
      id: "arrow",
      type: "checkbox",
      label: "Стрелка",
      initialValue: LINK_OPTIONS.arrow,
    },
    {
      id: "highlightByNodeLinkFading",
      type: "checkbox",
      label: "Затухание при анимации ноды",
      initialValue: LINK_OPTIONS.highlightByNodeLinkFading,
    },
    {
      id: "highlightByNodeArrowFading",
      type: "checkbox",
      label: "Затухание стрелки при анимации ноды",
      initialValue: LINK_OPTIONS.highlightByNodeArrowFading,
    },
    {
      id: "highlightByLinkLinkFading",
      type: "checkbox",
      label: "Затухание при анимации связи",
      initialValue: LINK_OPTIONS.highlightByLinkLinkFading,
    },
    {
      id: "highlightByLinkArrowFading",
      type: "checkbox",
      label: "Затухание стрелки при анимации связи",
      initialValue: LINK_OPTIONS.highlightByLinkArrowFading,
    },
    {
      id: "arrowReverseAppear",
      type: "checkbox",
      label: "Появление стрелки при анимации",
      initialValue: LINK_OPTIONS.arrowReverseAppear,
    },
  ];

  return keys ? LINK_CONTROLS.filter((control) => keys.includes(control.id)) : LINK_CONTROLS;
}
